lang: it-IT
title: PROGETTO HERMES
logo: /assets/icons/Hermes-logo.svg
email: ricerca@inrca.it
description: "DESCRIZIONE"
baseurl: "/jekyll-theme-basically-basic"
url: "https://bigimichele-beep.github.io"
repository: "bigimichele-beep/jekyll-theme-basically-basic"

# Tema locale: cartelle prese dalla root repo
layouts_dir: ../_layouts
includes_dir: ../_includes
sass:
  sass_dir: ../_sass
  style: compressed

markdown: kramdown
highlighter: rouge
lsi: false
incremental: false

# se vuoi usare i plugin standard
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

feed:
  path: atom.xml

paginate: 10
paginate_path: /page:num/

collections:
  recipes:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      read_time: true
